version: '3.9'
services:
  api:
    build: .
    container_name: api
    env_file:
      - env/.env.local
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/sharecode
      - JWT_KEY=a28afc6f-55b8-4546-83f1-2bf727e72539
      - CLIENT_ID=clientid
      - CLIENT_SECRET=clientsecret
      - RABBITMQ_HOST=queue
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASS=${RABBITMQ_DEFAULT_PASS}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:14
    container_name: db
    env_file:
      - env/.env.local
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
  queue:
    image: rabbitmq:3-management
    container_name: queue
    env_file:
      - env/.env.local
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 8080:15672
      - 5672:5672
    restart: always
  mongodb:
    image: mongo
    container_name: mongodb
    env_file:
      - env/.env.local
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_volume:/data/db
volumes:
  postgres_volume:
  mongodb_volume:
