version: '3.9'
services:
  # app:
  #   build: .
  #   container_name: app
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./:/usr/src/app
  #   restart: always
  #   depends_on:
  #     - db
  db:
    image: postgres:14
    container_name: postgres
    env_file:
      - db.env
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_volume:
