version: '3.9'
services:
  db:
    image: postgres:14
    container_name: postgres
    env_file:
      - db.env
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_volume:
