version: '3.9'
services:
  api:
    build: .
    container_name: api
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: db
    env_file:
      - db.env
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
  queue:
    image: rabbitmq:3-management
    container_name: queue
    env_file:
      - mq.env
    ports:
      - 8080:15672
      - 5672:5672
    restart: always
  mongodb:
    image: mongo
    container_name: mongodb
    env_file:
      - db.env
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_volume:/data/db
volumes:
  postgres_volume:
  mongodb_volume:
