name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    environment: development
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Node
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: yarn
    - name: Run tests
      env:
        JWT_KEY: ${{ secrets.JWT_KEY }}
      run: yarn jest
