name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v3
      
      - name: Set Up Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn ci
      - run: yarn install
      - run: yarn jest
